# Generated by Django 5.0.2 on 2024-02-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_creation_date_alter_ticket_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.ManyToManyField(blank=True, to='tickets.note'),
        ),
    ]
